[package]
name = "sysdc"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "^1.0.143", features = ["derive"] }
clap = { version = "^3.2.7", features = ["derive"] }
glob = "^0.3.0"
