version: "3"

services:
  proxy:
    image: envoyproxy/envoy:v1.24.0
    ports:
      - ${SYSDC_PORT}:50000
    volumes:
      - type: bind
        source: "./proxy/envoy.yaml"
        target: "/etc/envoy/envoy.yaml"
        read_only: true
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - doc
      - editor-front
  doc:
    image: klakegg/hugo:0.101.0-ext-alpine
    command: server --disableLiveReload --baseURL=${SYSDC_BASE_URL}/doc --appendPort=false
    volumes:
      - type: bind
        source: "./doc"
        target: "/src"
    environment:
      TZ: Asia/Tokyo
  editor-front:
    build: ./editor/front
    environment:
      TZ: Asia/Tokyo
  tool-storage:
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z.fips
    command: server /data
    environment:
      TZ: Asia/Tokyo
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpass
    volumes:
      - type: volume
        source: tool-storage-v
        target: "/data"

volumes:
  tool-storage-v:
    driver: local
