[package]
name = "sysdc_tool_json"
version = "1.0.1"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
serde_json = "1.0.83"
sysdc_parser = { path = "../../parser" }
