name: setup_libraries
runs:
  using: composite
  steps:
    - name: Update repository
      shell: bash
      run: sudo apt update
    - name: Install libraries
      shell: bash
      run: sudo apt install libdbus-1-dev libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev
