[package]
name = "sysdc_cli"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = "^1.0.143"
serde_json = "^1.0.83"
rmp-serde = "^1.1.0"
clap = { version = "^3.2.7", features = ["derive"] }
glob = "^0.3.0"
sysdc_parser = { path = "../parser" }
