[package]
name = "sysdc_parser"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "^1.0.143", features = ["derive"] }
rmp-serde = "^1.1.0"
anyhow = { version = "1.0.64", features = ["backtrace"] }
thiserror = "1.0.34"
