name: check

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup_libraries
    - uses: ./.github/actions/cache_cargo
    - name: Make dist dir
      run: mkdir -p tools/view/dist 
    - name: Build
      run: cargo build --all-targets

  fmt:
    runs-on: ubuntu-latest
    needs: cache
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache_cargo
    - name: Setup rustup
      run: rustup component add rustfmt
    - name: Check format
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    needs: cache
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup_libraries
    - uses: ./.github/actions/cache_cargo
    - name: Setup rustup
      run: rustup component add clippy
    - name: Make dist dir
      run: mkdir -p tools/view/dist
    - name: Check by Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    needs: cache
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup_libraries
    - uses: ./.github/actions/cache_cargo
    - name: Make dist dir
      run: mkdir -p tools/view/dist
    - name: Test
      run: cargo test --all
