name: release

on:
  push:
  #   branches:
  #     - "master"
  #     - "develop"

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cache_cargo
    - uses: ./.github/actions/setup_libraries
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Setup npm modules
      run: npm install
      working-directory: ./tools/view
    - name: Make dist dir
      run: mkdir -p ./tools/view/dist
    - name: Build
      run: cargo build --release
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
    - name: Upload to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/sysdc
        asset_name: sysdc-linux
